---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: heading
  label: Konten
- type: directory
  path: content/products
  label: Produk lokal
  create: all
  match: "**/*.md"
- type: document
  path: data/facility-tour.yml
  label: Fasilitas paket wisata
- type: document
  path: data/category-product.yml
  label: Kategori produk lokal
- type: document
  path: data/category-tour.yml
  label: Kategori paket wisata
upload_dir: static/images
public_path: https://web-tj.netlify.app/images
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
