---
label: Produk lokal
hide_body: true
display_field: name
fields:
- name: name
  type: text
  config:
    required: true
  label: Nama
  description: Nama produk
- name: photos
  type: field_group_list
  fields:
  - name: photo
    type: include
    config: {}
    template: foto
    label: Foto
  config:
    min: 
    max: 
    labelField: description
  label: Foto-foto
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Deskripsi
  description: Deskripsi produk secara lengkap yang menarik
- name: categories
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: documents
      section: kategori-produk-lokal-e7dd7756-bc74-4bf6-b156-20dd7bdd3303
      file: data/category-product.yml
      path: categories
  label: Kategori
  description: Kategori produk
- name: prices
  type: field_group_list
  fields:
  - name: price
    type: include
    config: {}
    template: harga
    label: Harga
  config:
    min: 
    max: 
    labelField: description
  label: List harga
  description: List semua harga (varian dari produk)
- name: promotions
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: documents
      section: promosi
      file: data/promotion.yml
      path: promotions
  label: Promosi
- name: notes
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Catatan
  description: Catatan untuk pembeli atau yang lainnya
- name: contact
  type: select
  default: []
  config:
    required: true
    options: []
    source:
      type: documents
      section: kontak-admin
      file: data/contact-admin.yml
      path: admins
  label: Kontak admin
pages:
- content/products/kelompok-saung-centong/set-alat-makan.md
