name: Trigger Netlify Build Hook
on:
  schedule:
    - cron: '0 * * * *'
env:
  NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
jobs:
  build:
    name: Request Netlify Build Hook
    runs-on: ubuntu-latest
    steps:
      - name: Request curl
        run: curl -X POST -d {} $NETLIFY_BUILD_HOOK
