name: Trigger Netlify Build
on:
  schedule:
    - cron: '*/3 * * * *'
jobs:
  build:
    name: Request Netlify Build Hook
    runs-on: ubuntu-latest
    steps:
      - name: Request curl
        env:
            NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        run: curl -X POST -d {} $NETLIFY_BUILD_HOOK
